title: A spark of a thought
description: Let's make life easier with simple scripting. Grateful for everyone's encouragement and support!
show_downloads: false
google_analytics: G-VD8N8M65XP
# remote_theme: jekyll-theme-dinky
theme: jekyll-theme-dinky

# From https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
# And from https://github.com/jekyll/minima/blob/master/_config.yml

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
future: true # GitHub pages will publish future posts
markdown: kramdown
highlighter: rouge
# permalink: /:year-:month-:day-:title/
date_format: "%Y.%m.%d"
# paginate: 5 - gives error "Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination."
# home_post_limit: 5
# show_excerpts: true

# kramdown:
#  input: GFM

# social_links:
#  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=TezrvRIAAAAJ&hl=en" }

# Exclude these files from production site
# exclude:
#  - CHANGELOG.md
#  - CNAME
#  - Gemfile
#  - Gemfile.lock
#  - LICENSE
#  - README.md
#  - screenshot.png
#  - docs/

plugins:
#  - jekyll-remote-theme
#  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-seo-tag
#  - jekyll-github-metadata
#  - jekyll-paginate
