title: A spark of a thought
description: Let's make life easier with simple scripting. Grateful for everyone's encouragement and support!
show_downloads: false
google_analytics: G-VD8N8M65XP
theme: jekyll-theme-dinky
